apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-aspnetcore-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-aspnetcore-pod
  template:
    metadata:
      labels:
        app: hello-aspnetcore-pod
    spec:
      containers:
      - name: hello-aspnetcore-container
        imagePullPolicy: Never
        image: hello-api:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /hello
            port: 80
        readinessProbe:
          httpGet:
            path: /hello
            port: 80
          # initialDelaySeconds: 30
          # periodSeconds: 5
